spring:
  application:
    name: ms-usermanagement
  profiles:
    active: prod
  cloud:
    config:
      profile: prod
      label: usermanagement
      name: ms
      uri: ${CONFIG_SERVER_URL:localhost:8888}